---
- hosts: all
  vars:
    web_server:
      log_flags: ''
  vars_prompt:
    - name: ssl_passphrase
      prompt: "Enter SSL Certificate Passphrase"
      private: true

  tasks:

    - action: shell whoami
      register: whoami

    - name: install packages
      apt: pkg={{ item }} state=present
      sudo: yes
      with_items:
        - nginx

    - name: disable nginx default site
      file: path=/etc/nginx/sites-enabled/default state=absent
      sudo: yes
      notify: restart nginx

    - name: configure nginx salad site
      template: src=templates/nginx-site dest=/etc/nginx/sites-available/salad
      sudo: yes

    - name: enable nginx salad site
      file: src=/etc/nginx/sites-available/salad dest=/etc/nginx/sites-enabled/salad owner={{ whoami.stdout }} group=www-data state=link
      sudo: yes
      notify: restart nginx

    - name: ensure /var/www/salad/ exists
      file: path=/var/www/salad state=directory recurse=yes owner={{ whoami.stdout }} group=www-data
      sudo: yes

    - name: add default index.html
      template: src=templates/index.html dest=/var/www/salad/index.html

    - name: ssl certs dir
      file: path=/etc/ssl/certs mode=755 state=directory owner=root
      sudo: yes
      tags: ssl

    - name: copy the certificate
      copy: src=certs/salad.entwicklerbier.org.crt dest=/etc/ssl/certs/salad.entwicklerbier.org.crt
      sudo: yes
      notify: restart nginx

    - name: copy the key
      copy: src=certs/salad.entwicklerbier.org.key dest=/etc/ssl/private/salad.entwicklerbier.secured.org.key
      sudo: yes
      notify: restart nginx

    - name: strip ssl keys
      command: openssl rsa -in /etc/ssl/private/salad.entwicklerbier.secured.org.key -out /etc/ssl/private/salad.entwicklerbier.org.key -passin pass:{{ssl_passphrase}} creates=/etc/ssl/private/salad.entwicklerbier.org.key
      sudo: yes
      notify: restart nginx

  handlers:

    - name: restart nginx
      sudo: yes
      action: service name=nginx state=restarted enabled=yes
