---
- hosts: all
  tasks:

    - action: shell whoami
      register: whoami

    - name: install packages
      apt: pkg={{ item }} state=present
      sudo: yes
      with_items:
        - nginx=1.4.6-1ubuntu3

    - name: disable nginx default site
      file: path=/etc/nginx/sites-available/default state=absent
      sudo: yes
      notify: restart nginx

    - name: configure nginx salad site
      template: src=templates/nginx-site dest=/etc/nginx/sites-available/salad
      sudo: yes

    - name: enable nginx salad site
      file: src=/etc/nginx/sites-available/salad dest=/etc/nginx/sites-enabled/salad owner={{ whoami.stdout }} group=www-data state=link
      sudo: yes
      notify: restart nginx

    - name: ensure /var/www/salad/ exists
      file: path=/var/www/salad state=directory recurse=yes owner={{ whoami.stdout }} group=www-data
      sudo: yes

    - name: add default index.html
      template: src=templates/index.html dest=/var/www/salad/index.html

  handlers:

    - name: restart nginx
      sudo: yes
      action: service name=nginx state=restarted enabled=yes
